import type { Preset } from './types';

export const presets: Preset[] = [
  {
    id: 'email',
    name: 'Email Address',
    category: 'Common',
    pattern: '[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}',
    flags: 'gi',
    description: 'Standard RFC 5321 compliant email address matching',
    testText: 'Contact us at support@example.com or sales@company.co.jp\nInvalid: @nodomain.com, missing@',
  },
  {
    id: 'iso-date',
    name: 'ISO 8601 Date',
    category: 'Common',
    pattern: '(?<year>\\d{4})-(?<month>0[1-9]|1[0-2])-(?<day>0[1-9]|[12]\\d|3[01])(?:T(?<hour>[01]\\d|2[0-3]):(?<min>[0-5]\\d):(?<sec>[0-5]\\d)(?:\\.(?<ms>\\d{1,3}))?(?<tz>Z|[+-][01]\\d:[0-5]\\d))?',
    flags: 'g',
    description: 'Full ISO 8601 with named capture groups for each component',
    testText: '2026-01-15\n2025-12-31T23:59:59Z\n2026-04-21T09:30:00.123+09:00\nInvalid: 2026-13-01, 2026/01/01',
  },
  {
    id: 'ipv4',
    name: 'IPv4 Address',
    category: 'Network',
    pattern: '\\b(?:(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]\\d|\\d)\\.){3}(?:25[0-5]|2[0-4]\\d|1\\d{2}|[1-9]\\d|\\d)\\b',
    flags: 'g',
    description: 'Validates each octet range (0-255)',
    testText: 'Server: 192.168.1.1\nPublic: 8.8.8.8, 1.1.1.1\nBroadcast: 255.255.255.255\nInvalid: 999.0.0.1, 192.168.1',
  },
  {
    id: 'url',
    name: 'URL (http/https)',
    category: 'Network',
    pattern: 'https?:\\/\\/(?:[\\w\\-]+\\.)+[\\w]{2,}(?:\\/[\\w\\-._~:/?#\\[\\]@!$&\'()*+,;=%]*)?',
    flags: 'gi',
    description: 'Matches http and https URLs',
    testText: 'Visit https://example.com/path?q=test#section\nAlso http://api.service.io/v2/users\nNot a URL: ftp://file.server.com',
  },
  {
    id: 'log',
    name: 'App Log Line',
    category: 'Logs',
    pattern: '\\[(?<ts>\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}\\.\\d{3})\\] \\[(?<level>ERROR|WARN|INFO|DEBUG|TRACE)\\] (?<logger>[\\w.]+): (?<msg>.+)',
    flags: 'gm',
    description: 'Structured application log parser with named groups',
    testText: '[2026-04-21 09:15:32.421] [INFO] com.app.Server: Started on port 8080\n[2026-04-21 09:15:33.001] [DEBUG] com.app.DB: Connection pool initialized\n[2026-04-21 09:16:01.777] [ERROR] com.app.Auth: Token validation failed for user_id=42\n[2026-04-21 09:16:02.003] [WARN] com.app.Rate: Rate limit reached ip=10.0.0.5',
  },
  {
    id: 'unicode-emoji',
    name: 'Unicode Emoji',
    category: 'Unicode (ES2024+)',
    pattern: '\\p{Emoji_Presentation}',
    flags: 'gu',
    description: 'Uses Unicode property escapes (\\p{}) — requires u or v flag',
    testText: 'Hello 👋 World 🌍\nLove ❤️ coffee ☕\nNo emoji here: :) :D',
  },
  {
    id: 'unicode-script',
    name: 'Japanese/CJK Script',
    category: 'Unicode (ES2024+)',
    pattern: '[\\p{Script=Hiragana}\\p{Script=Katakana}\\p{Script=Han}]+',
    flags: 'gu',
    description: 'Match Japanese characters using Unicode Script properties',
    testText: 'Hello World\n正規表現テスト2026\nMixed: RegexLab正規表現\nカタカナ + ひらがな',
  },
  {
    id: 'lookahead-px',
    name: 'Lookahead: numbers before px',
    category: 'Lookahead / Lookbehind',
    pattern: '\\d+(?=px)',
    flags: 'g',
    description: 'Positive lookahead — match digits only when followed by "px"',
    testText: 'width: 100px\nheight: 200px\nopacity: 0.5\nmargin: 16px 8px\nfont-size: 14px',
  },
  {
    id: 'lookbehind-price',
    name: 'Lookbehind: amounts after $',
    category: 'Lookahead / Lookbehind',
    pattern: '(?<=\\$)[\\d,]+(?:\\.\\d{2})?',
    flags: 'g',
    description: 'Positive lookbehind — match price after $ symbol',
    testText: 'Price: $1,299.99\nDiscount: $50.00\nTotal: $1,249.99\nNot matched: USD 500',
  },
  {
    id: 'named-groups-date',
    name: 'Named Groups (Date parts)',
    category: 'Groups',
    pattern: '(?<year>\\d{4})\\/(?<month>\\d{2})\\/(?<day>\\d{2})',
    flags: 'gd',
    description: 'Named capture groups + d flag for exact indices (ES2022)',
    testText: '2026/04/21\n1999/12/31\n2000/01/01',
  },
  {
    id: 'ai-email-validator',
    name: 'AI-Generated: Email Validator',
    category: 'AI Debug Challenge',
    pattern: '^(?:[a-z0-9!#$%&\'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&\'*+/=?^_`{|}~-]+)*|"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])$',
    flags: 'i',
    description: '⚠️ AI-generated RFC 5322 email regex — use this tool to verify it works correctly on your test cases',
    testText: 'valid@example.com\nuser.name+tag@sub.domain.co.uk\n"quoted@local"@example.com\nINVALID: @missing-local.com\nINVALID: two@@at.com\nINVALID: trailing-dot.@example.com',
    aiGenerated: true,
  },
  {
    id: 'ai-semver',
    name: 'AI-Generated: Semantic Version',
    category: 'AI Debug Challenge',
    pattern: '^(?P<major>0|[1-9]\\d*)\\.(?P<minor>0|[1-9]\\d*)\\.(?P<patch>0|[1-9]\\d*)(?:-(?P<prerelease>(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$',
    flags: 'g',
    description: '⚠️ AI used Python-style (?P<name>) groups — not valid in JS! Find and fix the bug.',
    testText: '1.0.0\n2.3.4-alpha.1\n0.0.1-beta+build.001\n1.0.0-rc.1+sha.abc123\nInvalid: 1.0, v1.0.0',
    aiGenerated: true,
  },
];

export const categories = [...new Set(presets.map(p => p.category))];
